### ISSUE TITLE
1.2.0 has breaking change

### ISSUE THREAD

**Issue by ashleygwilliams** [zeke/schemeless#1]
the new feature bump breaks the npm website :( here's the error:

```
/home/travis/build/npm/npm-website/node_modules/fs-plus/lib/fs-plus.js:708
  module.exports = new Proxy({}, {
                       ^
ReferenceError: Proxy is not defined
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/fs-plus/lib/fs-plus.js:708:24)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/fs-plus/lib/fs-plus.js:718:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/highlights/lib/highlights.js:8:8)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/highlights/lib/highlights.js:420:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/marky-markdown/lib/render.js:23:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/marky-markdown/index.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/presenters/package.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/agents/package.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/test/agents/package.js:10:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/travis/build/npm/npm-website/node_modules/lab/lib/cli.js:120:21
    at Array.forEach (native)
    at Object.internals.traverse.paths.forEach.testFiles [as traverse] (/home/travis/build/npm/npm-website/node_modules/lab/lib/cli.js:116:15)
    at Object.exports.run (/home/travis/build/npm/npm-website/node_modules/lab/lib/cli.js:61:31)
    at Object.<anonymous> (/home/travis/build/npm/npm-website/node_modules/lab/bin/lab:50:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by ashleygwilliams** [comment]
welp. nope this is something else that just happened to rear its head on the greenkeeper PR for this. sorry for the :fire: thanks for your hardwork.

**Comment by zeke** [comment]
Phew. Glad it wasn't me.

1.2.0 was just an addition to the readme: https://github.com/zeke/schemeless/commit/47ff023e44b801f948dc4c81cef2afd518986c48
